### ISSUE TITLE
Feature request: supporting DragonflyBSD?

### ISSUE THREAD

**Issue by chukcha-changa** [olevole/cbsd#66]
Hi olevole!
How feasible would it be to support **CBSD** on **DragonflyBSD**? I would really like to see CBSD on DF.

PS: Also I just wanted to say a very big thank you for all your hard work and a big well done to you all.

**Comment by olevole** [comment]
Hi, thank you for feedback. 

I've already tried to get CBSD on DragonFly, I also was interested. Unfortunately, the implementation of jail on DF is outdated. Everything you need to get CBSD on DF - is support jail.conf(5) configuration and libjail.so. I believe that for DF hackers it should be a trivial work, because in fact, jail did not develop more than 10+ years. Changing parameters from command line to jail.conf (with degradation of functional in the form of loss of ability to have jail on two interfaces) - that's all change for the period ;-)

**Comment by olevole** [comment]
Close issue  until better times because at the moment it does not have a possible solution
